version: '3'

services:
  keycloak:
    image: jboss/keycloak-openshift:4.0.0.Final
    container_name: keycloak
    command: ["start-keycloak.sh", "-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Djboss.socket.binding.port-offset=1000"]
    volumes:
    - $PWD/.docker/keycloak/realm-config:/opt/jboss/keycloak/realm-config
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    ports:
    - 9080:9080
    - 9444:9443
    - 10990:10990

  mongodb:
    image: centos/mongodb-36-centos7
    container_name: mongodb
    ports:
    - 27017:27017
    environment:
    - MONGODB_ADMIN_PASSWORD=cockpit321
    - MONGODB_DATABASE=cockpit
    - MONGODB_USER=mdbuser
    - MONGODB_PASSWORD=cockpit123
    volumes:
    - /tmp/sumo:/var/lib/mongodb/data

  api:
    build:
      context: .
      dockerfile: .docker/api/prod.dockerfile
    image: cockpit-api:latest
    container_name: api
    ports:
    - 3000:3000
    depends_on:
    - mongodb

  web:
      build:
        context: .
        dockerfile: .docker/cockpit/prod.dockerfile
      image: cockpit:latest
      container_name: web
      command: nginx -g 'daemon off;'
      volumes:
      - .docker/cockpit/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      ports:
      - 80:8080
      depends_on:
      - keycloak
      - api

volumes:
  uploads:
    driver: local
