apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb
  annotations:
  name: mongodb
spec:
  ports:
  - name: mongodb-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb
