apiVersion: v1
kind: Service
metadata:
  labels:
    app: cockpit-api
  annotations:
  name: cockpit-api
spec:
  ports:
  - name: cockpit-api-http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: cockpit-api
